// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderProject.Data;

namespace OrderProject.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211204185435_deneme")]
    partial class deneme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderProject.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Order", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 3,
                            CreatedOn = new DateTime(2021, 12, 4, 21, 54, 35, 51, DateTimeKind.Local).AddTicks(4412),
                            CustomerName = "Can Güler",
                            Price = 18m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            CreatedOn = new DateTime(2021, 12, 4, 21, 54, 35, 53, DateTimeKind.Local).AddTicks(5161),
                            CustomerName = "Mehmet Güler",
                            Price = 55m,
                            Status = 50,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CreatedOn = new DateTime(2021, 12, 4, 21, 54, 35, 53, DateTimeKind.Local).AddTicks(5306),
                            CustomerName = "Ahmet Güler",
                            Price = 60m,
                            Status = 10,
                            StoreName = "Shopi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
